"""
problem :

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

def fibo_numbers(nb):
    """Function that gives all the fibonacci numbers below the parameter"""

    list_fibo_numbers = [1, 1, 2]

    while list_fibo_numbers[-1] < nb:
    	list_fibo_numbers.append(list_fibo_numbers[-1] + list_fibo_numbers[-2])

    del list_fibo_numbers[-1]

    return list_fibo_numbers

print(sum([number for number in fibo_numbers(4000000) if number%2 == 0]))
